### ISSUE TITLE
文化墙设计

### ISSUE THREAD

**Issue by laozhou0731** [websoft9op/creation#1]
文化墙设计：
规格：618*1000mm。横向*2
要求：蓝色主色调，白色字，图2.5D风格，跟公司业务及文字内涵匹配；
时间：0107完成

**Comment by chendelin1982** [comment]
:sparkles: **Welcome to GitHub Projects** :sparkles:
We're so excited that you've decided to create a new project! Now that you're here, let's make sure you know how to get the most out of GitHub Projects.
- [x] Create a new project
- [x] Give your project a name
- [ ] Press the <kbd>?</kbd> key to see available keyboard shortcuts
- [ ] Add a new column
- [ ] Drag and drop this card to the new column
- [ ] Search for and add issues or PRs to your project
- [ ] Manage automation on columns
- [ ] [Archive a card](https://docs.github.com/articles/archiving-cards-on-a-project-board/) or archive all cards in a column

**Comment by chendelin1982** [comment]
1. 背景图片（一张图一分为二）+文字
2. 配英文
4. 一个logo+中英文
5. 物理银色边框 衬托 蓝色

**Comment by morning-tan** [comment]
背景图片因像素问题，暂时无法找到符合需求尺寸的图片，暂调整为两张图片。

**Comment by chendelin1982** [comment]
English
simple start, good finish 
trust team, create future

**Comment by morning-tan** [comment]
已提交第四版草图

**Comment by morning-tan** [comment]
1-8第六版定稿，1-9付印。

**Comment by laozhou0731** [comment]
定稿付印，费用100元，周一上墙.

**Comment by laozhou0731** [comment]
![文化墙](https://user-images.githubusercontent.com/62225175/104280779-65fa1980-54e7-11eb-860d-b7179d6fd6cd.jpg)
