### ISSUE TITLE
××× Print 印刷品设计

### ISSUE THREAD

**Issue by lujing0066** [websoft9op/creation#11]
**需求描述**

修改校园海报岗位信息

**使用场景**

请列出该设计的使用场景:

1. 展会
2. 招聘

**参考范例**

请参考链接https://github.com/websoft9op/recruitment/blob/main/jd/

 - 连接：联系方式、网址、二维码必不可少

**其他信息**
请在3月26日前完成，27、28日校招会需要使用。

**Comment by morning-tan** [comment]
3-23
文件已做好，保存在创客贴。因两所大学招聘审核未过，故印刷暂缓。issue关闭。
