### ISSUE TITLE
客户案例图 设计

### ISSUE THREAD

**Issue by laozhou0731** [websoft9op/creation#2]
**需求描述**

设计公司客户案例图

**使用场景**

1. 云市场商品详情页 客户案例
2. 官网 客户案例

**参考范例**

![image](https://user-images.githubusercontent.com/62225175/104795759-b32e0200-57eb-11eb-889f-dc600883656e.png)

**基本要求**

 - 类型：PNG
 - 像素：符合详情页最佳展示
 - 版权：商标、字体等务必保证合规性

**其他信息**

文字描述：140个国家和地区 20000+来自互联网、科技、教育、制造等行业的用户 在使用Websoft9的提供的高效云端生产力工具
案例再[扩充](https://www.websoft9.com/cn/cases/#)

**Comment by morning-tan** [comment]
计划1-21开始制作

**Comment by morning-tan** [comment]
1-26
定稿确认
