### ISSUE TITLE
7项软件著作权 新闻报道

### ISSUE THREAD

**Issue by chendelin1982** [websoft9op/creation#3]
**需求描述**

创作一篇关于公司获得7项软件著作权的文章

**使用场景**

请列出该设计的使用场景:

1. 博客
2. 公众号
3. 商业媒体

**参考范例**

如有参考范例，请截图：

**基本要求**

 - 图片：文章中需插入一张合并后的图片，证书【3×3】排列
 - 封面：科技型封面图
 - 版权：商标、字体等务必保证合规性
 - 广告法：严格遵守广告法，不能出现"最、第一"等极限用语

**其他信息**

描述其他所需的信息

**Comment by laozhou0731** [comment]
[blog](https://blog.websoft9.com/websoft9-approved-7ips/)
