### ISSUE TITLE
VMLab Logo 设计

### ISSUE THREAD

**Issue by chendelin1982** [websoft9op/creation#5]
**需求描述**

VMLab Logo 设计

**清单**

无需自行设计，从AI软件中选取一个：https://www.brandcrowd.com/maker/logos?text=VMLab&searchService=

然后再转换成矢量格式

**Comment by morning-tan** [comment]
LOGO确定截止时间：1-29

**Comment by morning-tan** [comment]
1-29
LOGO已初步确定。
![image](https://user-images.githubusercontent.com/54173243/106253522-8ef20c80-6252-11eb-9846-f7ce6174a4e7.png)
