### ISSUE TITLE
vmlab.top 一页网站设计

### ISSUE THREAD

**Issue by chendelin1982** [websoft9op/creation#6]
**需求描述**

vmlab.top 网站采用一页网站设计风格。  
实现方案：已经购买模板（存放在本项目：html/vmlab.top/static），只需针对模板内的信息和图片进行替换、修改即可
测试地址：https://websoft9op.github.io/creation/html/vmlab.top/static/

**项**

修改过程中，可能需要的工作包括

* logo, favicon, banner
* 每个栏目的图片
* 标题/介绍

**测试**

完成修改后需要多次测试，包括：

1. 菜单可用性
2. 外链可达
3. 速度

**Comment by morning-tan** [comment]
大图截止定稿时间：2月2日
