### ISSUE TITLE
创作一篇软文：白宫也用WordPress

### ISSUE THREAD

**Issue by chendelin1982** [websoft9op/creation#7]
**需求描述**

创作一篇关于 WordPress 可视化建站的软文：白宫也用WordPress，发布到阿里云和腾讯云社区，引导用户购买镜像

**使用场景**

请列出该设计的使用场景:

1. 博客
2. 科技社区媒体

**参考范例**

如有参考范例，请截图：

**基本要求**

 - 图片：文章中需插入5章【产品截图】
 - 封面：科技型封面图
 - 版权：商标、字体等务必保证合规性
 - 广告法：严格遵守广告法，不能出现"最、第一"等极限用语

**其他信息**

描述其他所需的信息

**Comment by laozhou0731** [comment]
https://blog.websoft9.com/whitehouse-site-wordpress-websoft9/   
博客已发
社区尝试去发
